name: Deploy to IIS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

#  BỎ bước setup-dotnet nếu đã cài sẵn
    # - name: Set up .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Check and stop processes using the folder
      run: |
        $path = "C:\webserver\net8iisdeploy"
        $lockedFiles = Get-Process | Where-Object { $_.Modules | Where-Object { $_.FileName -like "$path*" } }
        if ($lockedFiles) {
          $lockedFiles | Stop-Process -Force
        }

    - name: Deploy to IIS folder
      run: |
        iisreset /stop
        if (Test-Path "C:\webserver\net8iisdeploy") {
          if ((Get-Item "C:\webserver\net8iisdeploy").PSIsContainer) {
            Remove-Item -Recurse -Force "C:\webserver\net8iisdeploy" -ErrorAction SilentlyContinue
          } else {
            Remove-Item -Force "C:\webserver\net8iisdeploy" -ErrorAction SilentlyContinue
          }
        }
        New-Item -ItemType Directory -Path "C:\webserver\net8iisdeploy" -Force
        Copy-Item -Recurse -Force ./publish/* "C:\webserver\net8iisdeploy" -ErrorAction Stop
        iisreset /start
    - name: Restart IIS
      run: |
        iisreset
